=pod

=head1 NAME

 soya - start or stop soi platform applications

=head1 SYNOPSIS

 soya

=head1 DESCRIPTION 
 
 Soya se puede usar  para  iniciar  cualquier proceso via el comando screen,
 es un metascript que indicando los comandos en un archivo de configuracion,
 facilita la ejecucion de los mismos.

 Utiliza un directorio de configuracion, donde se almacenan los siguientes
 archivos:
  * soya.sh
    Aplicacion principal

  * soya.conf
    Archivo de configuracion de parametros de aplicacion

=head1 EXAMPLES

 Para activar una nueva aplicacion es necesario hacer lo siguiente:
 1. Crear una liga con el nombre de la aplicacion desde el directorio
    $HOME/soya/setup con el parametro start y stop, ej.
    ln -sf $HOME/soya/soya.sh $HOME/soya/setup/app.start 
    ln -sf $HOME/soya/soya.sh $HOME/soya/setup/app.stop 
 
 2. Crear un archivo de configuracion, donde se incluyan algunos de los
    parametros necesarios para la aplicacion, ej:
    # app.conf -- put here a short description.
    # -----------------------------------------
    apDebug=off
    apType=CT
    apCommand="sh ${HOME}/tomcat/bin/catalina.sh run"
 
=head1 AUTHOR

 soya v2.01
 (c) 2008, 2009 Nextel de Mexico 

 Written by
 Andres Aquino <andres.aquino@gmail.com>

=head1 BUGS

 Muchos!
      
 Se necesitan traductores... !!!

=cut
# vim: set ts=3 sw=3 sts=3 et si ai:
