#! /bin/sh

# Created:  10-JAN-2000 by Marc Beysel, LHS
# Additional script for gmd Watchdog gmddog
# It has to be cleaned up by the Administrator

# 2006-05-16: PM: shell scripts dropped -> "server operations"
#  -> PN 00272008:  All further info in application.ini !
#  This script is only for internal use from now ...i
#  If changing this script -> change application.ini also!
#  Decision taken:
#  "Makefile will be adapted to not copy START_GMD, STOP_GMD and
#  RESTART_GMD anymore to the output structure. They will not be
#  delivered to the customer anymore."

# first step: stop all worker except the gmddog

stop_md GMDCOM
stop_md GMDRES
stop_md GMDREC
stop_md GMDRRS
stop_md GMDRESDATA

# sleep between stopping and starting the Mediation Devices
sleep 60

START_GMD

# Delete preceeding hash marks to activate the gmdjan calls
#
# Compress all old log and error files which are uncompressed.
# Remove compressed files which are older than 30 days.
#gmdjan l -f -arm 30
#
# Remove requests from the database which 
# were completed at least 100 days ago.
#gmdjan r -f -arq 100
#
# Remove zombie edifact files
#gmdjan e -f
#
# Check the GMD's environment
#gmdjan c
