#!/bin/sh
# Created:  20-SEP-1999 by Marc Beysel, LHS
#
#
# This shell-script starts the GMD Request Response Server, the VMD,
# the GMD Response Parser, the GMDRESDATA and the GMD Recovery Process.
# It is important to start the modules in the given order.
#

# 2006-05-16: PM: shell scripts dropped -> "server operations"
#  -> PN 00272008:  All further info in application.ini !
#  This script is only for internal use from now ...i
#  If changing this script -> change application.ini also!
#  Decision taken:
#  "Makefile will be adapted to not copy START_GMD, STOP_GMD and
#  RESTART_GMD anymore to the output structure. They will not be
#  delivered to the customer anymore."

# define VMD (can be done by operators)
# important note: for the start the VMDWatchdog please run it background :
#                  f.e. : VMD="/app/bscs/bin/VMDWatchdog -r3 &"
VMD=vmd

# number of gmdcom's  (can be changed by operators)
GMDCOM_NR=1

# number of gmdres's (can be changed by operators)
GMDRES_NR=1

# number of gmdrec's (can be changed by operators)
GMDREC_NR=1

# number of gmdresdata's (can be changed by operators)
GMDRESDATA_NR=1


# reading command line

for COMARG in $*
do
	CHECKER=0
	case	$COMARG in
			-t) 	TRACE_MODE="-t"
				CHECKER=1
			;;
	esac
	
# unknown parameter

	if [ $CHECKER = 0 ]
	then
		echo "usage: START_GMD [-t]"
		exit
	fi
done



# start GMDRRS
# GMDRRS can be started one time only!
echo "starting GMDRRS ..."
gmdrrs $1 &


#start VMD
if [ -z "$VMD" ]
then
	echo "VMD not defined"
	exit
else
	echo "starting VMD ..."
	$VMD	
fi


echo
echo "start $GMDCOM_NR instance(s) of GMDCOM"
echo

COUNTER=1
while [ $COUNTER -le $GMDCOM_NR ]
do
	echo "starting $COUNTER. instance of GMDCOM..."
	gmdcom $1 &
	COUNTER=`(echo $COUNTER + 1 | bc)`
done


echo
echo "start $GMDRES_NR instance(s) of GMDRES"
echo

COUNTER=1
while [ $COUNTER -le $GMDRES_NR ]
do
	echo "starting $COUNTER. instance of GMDRES..."
	gmdres $1 &
	COUNTER=`(echo $COUNTER + 1 | bc)`
done


echo
echo "start $GMDREC_NR instance(s) of GMDREC"
echo

COUNTER=1
while [ $COUNTER -le $GMDREC_NR ]
do
	echo "starting $COUNTER. instance of GMDREC..."
	gmdrec $1 &
	COUNTER=`(echo $COUNTER + 1 | bc)`
done


echo
echo "start $GMDRESDATA_NR instance(s) of GMDRESDATA"
echo

COUNTER=1
while [ $COUNTER -le $GMDRESDATA_NR ]
do
	echo "starting $COUNTER. instance of GMDRESDATA..."
	gmdresdata $1 &
	COUNTER=`(echo $COUNTER + 1 | bc)`
done




