#!/bin/sh
#
# Start TCH Tax Calculation Handler
#
#/*****************************************************************************
# * SchlumbergerSema 1998-2003
# *
# * All rights reserved.
# * Copying of this software or parts of this software is a violation of German
# * and International copyright laws.  
# *
# * Project:    Dublin USA
# * File:       Makefile                     Tax Calculation Handler (TCH)
# * Created:    June 29, 2001
# * Author(s):  Dennis Vogel
# * Modification
# *   2003-May-15: D237667: Dr. Dirk Heumann: Include SCCS version strings.
# *****************************************************************************/

# SCCS_VERSION = "bsst_main/bscs/batch/src/tch/START_TCH, , I_BSCSIX_R2_NMX04.01, I_BSCSIX_R2_NMX04.01_090318, 2004/04/30, /main/1";

lpid=""
lpid=`ps -e | grep " tch" | grep -v "grep" | awk '{print $1}'`

if [ "$lpid" != "" ]
then
    echo "An TCH server is already running, process id is $lpid, no new TCH will be started"
    ps -ef | grep " tch" | grep -v "grep"
    exit -1
fi


#
# Start the TCH
#
#
# usage: tch [-i] [-d] [-t] [-o timeOut in seconds] [-p Port number] [-f log File directory path]
#   -i : Prints version and usage information and exits
#   -d : Debug Mode
#   -t : Trace option
#   -p : Port Number for server to connect to
#   -f : Log File Directory path (do not put a trailing '/'
#   -o : TimeOut in seconds server waits on 
#   -c : Specifies an optional configuration file and path.
#
#   log filename: TCH_YYYYMMDD.log
#

#nohup tch -i &              # Prints version and usage information and exits
#nohup tch -d &              # turn on debug mode
#nohup tch -t &              # turn on trace mode (Dumps lots of buffer data)
#nohup tch -p xxxxx &        # Server connects to this port number (For debug use)
#nohup tch -f /xxx/xxx &     # specify directory path for log file (no trailing '/')
#nohup tch -o 33 &           # Timeout after 33 seconds while waiting for receive data
#nohup tch -c /xxx/tch.cfg & # specify directory path and file name for configuration data

echo "SCRIPT:Starting tch..."
echo "SCRIPT:redirecting stdout and stderr to ./TCH_NOHUP.log "

#Full Debug and Trace Version
#nohup tch -dt -f /xxx/xx -o 33 >> TCH_NOHUP.log 2>> TCH_NOHUP.log &
#Use Configuration file instead of command line parameters
#nohup tch -c /xxx/tch.cfg >> TCH_NOHUP.log 2>> TCH_NOHUP.log &

#Production version
nohup tch >> TCH_NOHUP.log 2>> TCH_NOHUP.log &

lpid=""
# Sleep long enough to see if TCH got past initialization.
sleep 5
lpid=`ps -e | grep " tch" | grep -v "grep" | awk '{print $1}'`

if [ "$lpid" != "" ]
then
    echo "SCRIPT:TCH server running, process id is $lpid"
    ps -ef | grep " tch" | grep -v "grep"
else
    echo "SCRIPT:ERROR TCH server is not running"
fi
