#! /bin/sh
#
# Created:  20-SEP-1999 by Marc Beysel, LHS
#

#  2006-05-16: PM: shell scripts dropped -> "server operations"
#  -> PN 00272008: All further info in application.ini !
#  This script is only for internal use from now ...i
#  If changing this script -> change application.ini also!
#  Decision taken:
#  "Makefile will be adapted to not copy START_GMD, STOP_GMD and
#  RESTART_GMD anymore to the output structure. They will not be
#  delivered to the customer anymore."



stop_md ALL



