#!/bin/sh
#
# Stop TCH Tax Calculation Handler
#
#/*****************************************************************************
# * SchlumbergerSema 1998-2003
# *
# * All rights reserved.
# * Copying of this software or parts of this software is a violation of German
# * and International copyright laws.  
# *
# * Project:    Dublin USA
# * File:       Makefile                     Tax Calculation Handler (TCH)
# * Created:    June 29, 2001
# * Author(s):  Dennis Vogel
# * Modification
# *   2003-May-15: D237667: Dr. Dirk Heumann: Include SCCS version strings.
# *****************************************************************************/

# SCCS_VERSION = "bsst_main/bscs/batch/src/tch/STOP_TCH, , I_BSCSIX_R2_NMX04.01, I_BSCSIX_R2_NMX04.01_090318, 2004/04/30, /main/1";

ps -ef | grep " tch" | grep -v "grep"
user=$1
lpid=""
lpid=`ps -e | grep " tch" | grep -v "grep" | awk '{print $1}'`

if [ "$lpid" != "" ]
then
    echo "TCH process id is $lpid, TCH is being shutdown"
    kill  $lpid
    sleep 5
    lpid=""
    lpid=`ps -e | grep " tch" | grep -v "grep" | awk '{print $1}'`
    if [ "$lpid" != "" ]
    then
        echo "TCH process still running process id=$lpid"
        ps -ef | grep " tch" | grep -v "grep"
    else
        echo "TCH has been shutdown"
    fi
else
    echo "There is no TCH process to stop"
fi
